development:
  adapter: postgresql
  encoding: unicode
  database: heli_development
  template: template0
  pool: 5
  timeout: 5000
  username: myuser
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: heli_test
  template: template0
  pool: 5
  timeout: 5000
  username: myuser
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: heli_production
  template: template0
  pool: 5
  timeout: 5000
  username: myuser
  password:
