require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FblUnitsController do

  # This should return the minimal set of attributes required to create a valid
  # FblUnit. As you add validations to FblUnit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FblUnitsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fbl_units as @fbl_units" do
      fbl_unit = FblUnit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fbl_units).should eq([fbl_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested fbl_unit as @fbl_unit" do
      fbl_unit = FblUnit.create! valid_attributes
      get :show, {:id => fbl_unit.to_param}, valid_session
      assigns(:fbl_unit).should eq(fbl_unit)
    end
  end

  describe "GET new" do
    it "assigns a new fbl_unit as @fbl_unit" do
      get :new, {}, valid_session
      assigns(:fbl_unit).should be_a_new(FblUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested fbl_unit as @fbl_unit" do
      fbl_unit = FblUnit.create! valid_attributes
      get :edit, {:id => fbl_unit.to_param}, valid_session
      assigns(:fbl_unit).should eq(fbl_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FblUnit" do
        expect {
          post :create, {:fbl_unit => valid_attributes}, valid_session
        }.to change(FblUnit, :count).by(1)
      end

      it "assigns a newly created fbl_unit as @fbl_unit" do
        post :create, {:fbl_unit => valid_attributes}, valid_session
        assigns(:fbl_unit).should be_a(FblUnit)
        assigns(:fbl_unit).should be_persisted
      end

      it "redirects to the created fbl_unit" do
        post :create, {:fbl_unit => valid_attributes}, valid_session
        response.should redirect_to(FblUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fbl_unit as @fbl_unit" do
        # Trigger the behavior that occurs when invalid params are submitted
        FblUnit.any_instance.stub(:save).and_return(false)
        post :create, {:fbl_unit => {}}, valid_session
        assigns(:fbl_unit).should be_a_new(FblUnit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FblUnit.any_instance.stub(:save).and_return(false)
        post :create, {:fbl_unit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fbl_unit" do
        fbl_unit = FblUnit.create! valid_attributes
        # Assuming there are no other fbl_units in the database, this
        # specifies that the FblUnit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FblUnit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fbl_unit.to_param, :fbl_unit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fbl_unit as @fbl_unit" do
        fbl_unit = FblUnit.create! valid_attributes
        put :update, {:id => fbl_unit.to_param, :fbl_unit => valid_attributes}, valid_session
        assigns(:fbl_unit).should eq(fbl_unit)
      end

      it "redirects to the fbl_unit" do
        fbl_unit = FblUnit.create! valid_attributes
        put :update, {:id => fbl_unit.to_param, :fbl_unit => valid_attributes}, valid_session
        response.should redirect_to(fbl_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the fbl_unit as @fbl_unit" do
        fbl_unit = FblUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FblUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => fbl_unit.to_param, :fbl_unit => {}}, valid_session
        assigns(:fbl_unit).should eq(fbl_unit)
      end

      it "re-renders the 'edit' template" do
        fbl_unit = FblUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FblUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => fbl_unit.to_param, :fbl_unit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fbl_unit" do
      fbl_unit = FblUnit.create! valid_attributes
      expect {
        delete :destroy, {:id => fbl_unit.to_param}, valid_session
      }.to change(FblUnit, :count).by(-1)
    end

    it "redirects to the fbl_units list" do
      fbl_unit = FblUnit.create! valid_attributes
      delete :destroy, {:id => fbl_unit.to_param}, valid_session
      response.should redirect_to(fbl_units_url)
    end
  end

end
