require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaddlesController do

  # This should return the minimal set of attributes required to create a valid
  # Paddle. As you add validations to Paddle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaddlesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paddles as @paddles" do
      paddle = Paddle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paddles).should eq([paddle])
    end
  end

  describe "GET show" do
    it "assigns the requested paddle as @paddle" do
      paddle = Paddle.create! valid_attributes
      get :show, {:id => paddle.to_param}, valid_session
      assigns(:paddle).should eq(paddle)
    end
  end

  describe "GET new" do
    it "assigns a new paddle as @paddle" do
      get :new, {}, valid_session
      assigns(:paddle).should be_a_new(Paddle)
    end
  end

  describe "GET edit" do
    it "assigns the requested paddle as @paddle" do
      paddle = Paddle.create! valid_attributes
      get :edit, {:id => paddle.to_param}, valid_session
      assigns(:paddle).should eq(paddle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Paddle" do
        expect {
          post :create, {:paddle => valid_attributes}, valid_session
        }.to change(Paddle, :count).by(1)
      end

      it "assigns a newly created paddle as @paddle" do
        post :create, {:paddle => valid_attributes}, valid_session
        assigns(:paddle).should be_a(Paddle)
        assigns(:paddle).should be_persisted
      end

      it "redirects to the created paddle" do
        post :create, {:paddle => valid_attributes}, valid_session
        response.should redirect_to(Paddle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paddle as @paddle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paddle.any_instance.stub(:save).and_return(false)
        post :create, {:paddle => {}}, valid_session
        assigns(:paddle).should be_a_new(Paddle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paddle.any_instance.stub(:save).and_return(false)
        post :create, {:paddle => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paddle" do
        paddle = Paddle.create! valid_attributes
        # Assuming there are no other paddles in the database, this
        # specifies that the Paddle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Paddle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => paddle.to_param, :paddle => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested paddle as @paddle" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => valid_attributes}, valid_session
        assigns(:paddle).should eq(paddle)
      end

      it "redirects to the paddle" do
        paddle = Paddle.create! valid_attributes
        put :update, {:id => paddle.to_param, :paddle => valid_attributes}, valid_session
        response.should redirect_to(paddle)
      end
    end

    describe "with invalid params" do
      it "assigns the paddle as @paddle" do
        paddle = Paddle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paddle.any_instance.stub(:save).and_return(false)
        put :update, {:id => paddle.to_param, :paddle => {}}, valid_session
        assigns(:paddle).should eq(paddle)
      end

      it "re-renders the 'edit' template" do
        paddle = Paddle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paddle.any_instance.stub(:save).and_return(false)
        put :update, {:id => paddle.to_param, :paddle => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paddle" do
      paddle = Paddle.create! valid_attributes
      expect {
        delete :destroy, {:id => paddle.to_param}, valid_session
      }.to change(Paddle, :count).by(-1)
    end

    it "redirects to the paddles list" do
      paddle = Paddle.create! valid_attributes
      delete :destroy, {:id => paddle.to_param}, valid_session
      response.should redirect_to(paddles_url)
    end
  end

end
