require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RudderGyrosController do

  # This should return the minimal set of attributes required to create a valid
  # RudderGyro. As you add validations to RudderGyro, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RudderGyrosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rudder_gyros as @rudder_gyros" do
      rudder_gyro = RudderGyro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rudder_gyros).should eq([rudder_gyro])
    end
  end

  describe "GET show" do
    it "assigns the requested rudder_gyro as @rudder_gyro" do
      rudder_gyro = RudderGyro.create! valid_attributes
      get :show, {:id => rudder_gyro.to_param}, valid_session
      assigns(:rudder_gyro).should eq(rudder_gyro)
    end
  end

  describe "GET new" do
    it "assigns a new rudder_gyro as @rudder_gyro" do
      get :new, {}, valid_session
      assigns(:rudder_gyro).should be_a_new(RudderGyro)
    end
  end

  describe "GET edit" do
    it "assigns the requested rudder_gyro as @rudder_gyro" do
      rudder_gyro = RudderGyro.create! valid_attributes
      get :edit, {:id => rudder_gyro.to_param}, valid_session
      assigns(:rudder_gyro).should eq(rudder_gyro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RudderGyro" do
        expect {
          post :create, {:rudder_gyro => valid_attributes}, valid_session
        }.to change(RudderGyro, :count).by(1)
      end

      it "assigns a newly created rudder_gyro as @rudder_gyro" do
        post :create, {:rudder_gyro => valid_attributes}, valid_session
        assigns(:rudder_gyro).should be_a(RudderGyro)
        assigns(:rudder_gyro).should be_persisted
      end

      it "redirects to the created rudder_gyro" do
        post :create, {:rudder_gyro => valid_attributes}, valid_session
        response.should redirect_to(RudderGyro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rudder_gyro as @rudder_gyro" do
        # Trigger the behavior that occurs when invalid params are submitted
        RudderGyro.any_instance.stub(:save).and_return(false)
        post :create, {:rudder_gyro => {}}, valid_session
        assigns(:rudder_gyro).should be_a_new(RudderGyro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RudderGyro.any_instance.stub(:save).and_return(false)
        post :create, {:rudder_gyro => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rudder_gyro" do
        rudder_gyro = RudderGyro.create! valid_attributes
        # Assuming there are no other rudder_gyros in the database, this
        # specifies that the RudderGyro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RudderGyro.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rudder_gyro.to_param, :rudder_gyro => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rudder_gyro as @rudder_gyro" do
        rudder_gyro = RudderGyro.create! valid_attributes
        put :update, {:id => rudder_gyro.to_param, :rudder_gyro => valid_attributes}, valid_session
        assigns(:rudder_gyro).should eq(rudder_gyro)
      end

      it "redirects to the rudder_gyro" do
        rudder_gyro = RudderGyro.create! valid_attributes
        put :update, {:id => rudder_gyro.to_param, :rudder_gyro => valid_attributes}, valid_session
        response.should redirect_to(rudder_gyro)
      end
    end

    describe "with invalid params" do
      it "assigns the rudder_gyro as @rudder_gyro" do
        rudder_gyro = RudderGyro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RudderGyro.any_instance.stub(:save).and_return(false)
        put :update, {:id => rudder_gyro.to_param, :rudder_gyro => {}}, valid_session
        assigns(:rudder_gyro).should eq(rudder_gyro)
      end

      it "re-renders the 'edit' template" do
        rudder_gyro = RudderGyro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RudderGyro.any_instance.stub(:save).and_return(false)
        put :update, {:id => rudder_gyro.to_param, :rudder_gyro => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rudder_gyro" do
      rudder_gyro = RudderGyro.create! valid_attributes
      expect {
        delete :destroy, {:id => rudder_gyro.to_param}, valid_session
      }.to change(RudderGyro, :count).by(-1)
    end

    it "redirects to the rudder_gyros list" do
      rudder_gyro = RudderGyro.create! valid_attributes
      delete :destroy, {:id => rudder_gyro.to_param}, valid_session
      response.should redirect_to(rudder_gyros_url)
    end
  end

end
