require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpeedControlsController do

  # This should return the minimal set of attributes required to create a valid
  # SpeedControl. As you add validations to SpeedControl, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpeedControlsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all speed_controls as @speed_controls" do
      speed_control = SpeedControl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:speed_controls).should eq([speed_control])
    end
  end

  describe "GET show" do
    it "assigns the requested speed_control as @speed_control" do
      speed_control = SpeedControl.create! valid_attributes
      get :show, {:id => speed_control.to_param}, valid_session
      assigns(:speed_control).should eq(speed_control)
    end
  end

  describe "GET new" do
    it "assigns a new speed_control as @speed_control" do
      get :new, {}, valid_session
      assigns(:speed_control).should be_a_new(SpeedControl)
    end
  end

  describe "GET edit" do
    it "assigns the requested speed_control as @speed_control" do
      speed_control = SpeedControl.create! valid_attributes
      get :edit, {:id => speed_control.to_param}, valid_session
      assigns(:speed_control).should eq(speed_control)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpeedControl" do
        expect {
          post :create, {:speed_control => valid_attributes}, valid_session
        }.to change(SpeedControl, :count).by(1)
      end

      it "assigns a newly created speed_control as @speed_control" do
        post :create, {:speed_control => valid_attributes}, valid_session
        assigns(:speed_control).should be_a(SpeedControl)
        assigns(:speed_control).should be_persisted
      end

      it "redirects to the created speed_control" do
        post :create, {:speed_control => valid_attributes}, valid_session
        response.should redirect_to(SpeedControl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved speed_control as @speed_control" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpeedControl.any_instance.stub(:save).and_return(false)
        post :create, {:speed_control => {}}, valid_session
        assigns(:speed_control).should be_a_new(SpeedControl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpeedControl.any_instance.stub(:save).and_return(false)
        post :create, {:speed_control => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested speed_control" do
        speed_control = SpeedControl.create! valid_attributes
        # Assuming there are no other speed_controls in the database, this
        # specifies that the SpeedControl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpeedControl.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => speed_control.to_param, :speed_control => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested speed_control as @speed_control" do
        speed_control = SpeedControl.create! valid_attributes
        put :update, {:id => speed_control.to_param, :speed_control => valid_attributes}, valid_session
        assigns(:speed_control).should eq(speed_control)
      end

      it "redirects to the speed_control" do
        speed_control = SpeedControl.create! valid_attributes
        put :update, {:id => speed_control.to_param, :speed_control => valid_attributes}, valid_session
        response.should redirect_to(speed_control)
      end
    end

    describe "with invalid params" do
      it "assigns the speed_control as @speed_control" do
        speed_control = SpeedControl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpeedControl.any_instance.stub(:save).and_return(false)
        put :update, {:id => speed_control.to_param, :speed_control => {}}, valid_session
        assigns(:speed_control).should eq(speed_control)
      end

      it "re-renders the 'edit' template" do
        speed_control = SpeedControl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpeedControl.any_instance.stub(:save).and_return(false)
        put :update, {:id => speed_control.to_param, :speed_control => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested speed_control" do
      speed_control = SpeedControl.create! valid_attributes
      expect {
        delete :destroy, {:id => speed_control.to_param}, valid_session
      }.to change(SpeedControl, :count).by(-1)
    end

    it "redirects to the speed_controls list" do
      speed_control = SpeedControl.create! valid_attributes
      delete :destroy, {:id => speed_control.to_param}, valid_session
      response.should redirect_to(speed_controls_url)
    end
  end

end
