require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TailBladesController do

  # This should return the minimal set of attributes required to create a valid
  # TailBlade. As you add validations to TailBlade, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TailBladesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tail_blades as @tail_blades" do
      tail_blade = TailBlade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tail_blades).should eq([tail_blade])
    end
  end

  describe "GET show" do
    it "assigns the requested tail_blade as @tail_blade" do
      tail_blade = TailBlade.create! valid_attributes
      get :show, {:id => tail_blade.to_param}, valid_session
      assigns(:tail_blade).should eq(tail_blade)
    end
  end

  describe "GET new" do
    it "assigns a new tail_blade as @tail_blade" do
      get :new, {}, valid_session
      assigns(:tail_blade).should be_a_new(TailBlade)
    end
  end

  describe "GET edit" do
    it "assigns the requested tail_blade as @tail_blade" do
      tail_blade = TailBlade.create! valid_attributes
      get :edit, {:id => tail_blade.to_param}, valid_session
      assigns(:tail_blade).should eq(tail_blade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TailBlade" do
        expect {
          post :create, {:tail_blade => valid_attributes}, valid_session
        }.to change(TailBlade, :count).by(1)
      end

      it "assigns a newly created tail_blade as @tail_blade" do
        post :create, {:tail_blade => valid_attributes}, valid_session
        assigns(:tail_blade).should be_a(TailBlade)
        assigns(:tail_blade).should be_persisted
      end

      it "redirects to the created tail_blade" do
        post :create, {:tail_blade => valid_attributes}, valid_session
        response.should redirect_to(TailBlade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tail_blade as @tail_blade" do
        # Trigger the behavior that occurs when invalid params are submitted
        TailBlade.any_instance.stub(:save).and_return(false)
        post :create, {:tail_blade => {}}, valid_session
        assigns(:tail_blade).should be_a_new(TailBlade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TailBlade.any_instance.stub(:save).and_return(false)
        post :create, {:tail_blade => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tail_blade" do
        tail_blade = TailBlade.create! valid_attributes
        # Assuming there are no other tail_blades in the database, this
        # specifies that the TailBlade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TailBlade.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tail_blade.to_param, :tail_blade => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tail_blade as @tail_blade" do
        tail_blade = TailBlade.create! valid_attributes
        put :update, {:id => tail_blade.to_param, :tail_blade => valid_attributes}, valid_session
        assigns(:tail_blade).should eq(tail_blade)
      end

      it "redirects to the tail_blade" do
        tail_blade = TailBlade.create! valid_attributes
        put :update, {:id => tail_blade.to_param, :tail_blade => valid_attributes}, valid_session
        response.should redirect_to(tail_blade)
      end
    end

    describe "with invalid params" do
      it "assigns the tail_blade as @tail_blade" do
        tail_blade = TailBlade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TailBlade.any_instance.stub(:save).and_return(false)
        put :update, {:id => tail_blade.to_param, :tail_blade => {}}, valid_session
        assigns(:tail_blade).should eq(tail_blade)
      end

      it "re-renders the 'edit' template" do
        tail_blade = TailBlade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TailBlade.any_instance.stub(:save).and_return(false)
        put :update, {:id => tail_blade.to_param, :tail_blade => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tail_blade" do
      tail_blade = TailBlade.create! valid_attributes
      expect {
        delete :destroy, {:id => tail_blade.to_param}, valid_session
      }.to change(TailBlade, :count).by(-1)
    end

    it "redirects to the tail_blades list" do
      tail_blade = TailBlade.create! valid_attributes
      delete :destroy, {:id => tail_blade.to_param}, valid_session
      response.should redirect_to(tail_blades_url)
    end
  end

end
