require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThrottleServosController do

  # This should return the minimal set of attributes required to create a valid
  # ThrottleServo. As you add validations to ThrottleServo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThrottleServosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all throttle_servos as @throttle_servos" do
      throttle_servo = ThrottleServo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:throttle_servos).should eq([throttle_servo])
    end
  end

  describe "GET show" do
    it "assigns the requested throttle_servo as @throttle_servo" do
      throttle_servo = ThrottleServo.create! valid_attributes
      get :show, {:id => throttle_servo.to_param}, valid_session
      assigns(:throttle_servo).should eq(throttle_servo)
    end
  end

  describe "GET new" do
    it "assigns a new throttle_servo as @throttle_servo" do
      get :new, {}, valid_session
      assigns(:throttle_servo).should be_a_new(ThrottleServo)
    end
  end

  describe "GET edit" do
    it "assigns the requested throttle_servo as @throttle_servo" do
      throttle_servo = ThrottleServo.create! valid_attributes
      get :edit, {:id => throttle_servo.to_param}, valid_session
      assigns(:throttle_servo).should eq(throttle_servo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThrottleServo" do
        expect {
          post :create, {:throttle_servo => valid_attributes}, valid_session
        }.to change(ThrottleServo, :count).by(1)
      end

      it "assigns a newly created throttle_servo as @throttle_servo" do
        post :create, {:throttle_servo => valid_attributes}, valid_session
        assigns(:throttle_servo).should be_a(ThrottleServo)
        assigns(:throttle_servo).should be_persisted
      end

      it "redirects to the created throttle_servo" do
        post :create, {:throttle_servo => valid_attributes}, valid_session
        response.should redirect_to(ThrottleServo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved throttle_servo as @throttle_servo" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThrottleServo.any_instance.stub(:save).and_return(false)
        post :create, {:throttle_servo => {}}, valid_session
        assigns(:throttle_servo).should be_a_new(ThrottleServo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThrottleServo.any_instance.stub(:save).and_return(false)
        post :create, {:throttle_servo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested throttle_servo" do
        throttle_servo = ThrottleServo.create! valid_attributes
        # Assuming there are no other throttle_servos in the database, this
        # specifies that the ThrottleServo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ThrottleServo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => throttle_servo.to_param, :throttle_servo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested throttle_servo as @throttle_servo" do
        throttle_servo = ThrottleServo.create! valid_attributes
        put :update, {:id => throttle_servo.to_param, :throttle_servo => valid_attributes}, valid_session
        assigns(:throttle_servo).should eq(throttle_servo)
      end

      it "redirects to the throttle_servo" do
        throttle_servo = ThrottleServo.create! valid_attributes
        put :update, {:id => throttle_servo.to_param, :throttle_servo => valid_attributes}, valid_session
        response.should redirect_to(throttle_servo)
      end
    end

    describe "with invalid params" do
      it "assigns the throttle_servo as @throttle_servo" do
        throttle_servo = ThrottleServo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThrottleServo.any_instance.stub(:save).and_return(false)
        put :update, {:id => throttle_servo.to_param, :throttle_servo => {}}, valid_session
        assigns(:throttle_servo).should eq(throttle_servo)
      end

      it "re-renders the 'edit' template" do
        throttle_servo = ThrottleServo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThrottleServo.any_instance.stub(:save).and_return(false)
        put :update, {:id => throttle_servo.to_param, :throttle_servo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested throttle_servo" do
      throttle_servo = ThrottleServo.create! valid_attributes
      expect {
        delete :destroy, {:id => throttle_servo.to_param}, valid_session
      }.to change(ThrottleServo, :count).by(-1)
    end

    it "redirects to the throttle_servos list" do
      throttle_servo = ThrottleServo.create! valid_attributes
      delete :destroy, {:id => throttle_servo.to_param}, valid_session
      response.should redirect_to(throttle_servos_url)
    end
  end

end
